version: '3.8'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana-data: {}
  mysql_data: {}
  django_config: {}

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: recipe_db
      MYSQL_USER: recipe_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - monitoring

  backend:
    image: vadsimus8/recipe:latest  # Используем образ из Docker Hub
    container_name: django
    ports:
      - "8095:8095"
    networks:
      - monitoring
    environment:
      - DJANGO_SETTINGS_MODULE=recipe.settings
    depends_on:
      - mysql
    volumes:
      - ./recipe/config:/app/config
      - django_config:/app/config_data
    command: >
      sh -c "
      until nc -z mysql 3306; do
        echo 'Waiting for MySQL...';
        sleep 2;
      done;
      python manage.py migrate &&
      uvicorn recipe.asgi:application --host 0.0.0.0 --port 8095"

  frontend:
    build:
      context: ./recipe-fe
    container_name: recipe-fe
    ports:
      - "80:80"
    networks:
      - monitoring
    depends_on:
      - backend
    volumes:
      - ./recipe-fe/nginx.conf:/etc/nginx/nginx.conf:ro

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - monitoring