# Generated by Django 5.0.4 on 2024-05-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_ingredient_cost_recipe_description_recipe_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
