# Generated by Django 5.0.4 on 2025-08-12 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_remove_recipe_image_url_recipe_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(
                choices=[('l', 'литры'), ('g', 'граммы'), ('pcs', 'штуки')], default='g', max_length=3
            ),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'unit', 'user')},
        ),
    ]
