# Generated by Django 5.0.4 on 2025-12-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_alter_ingredient_unique_together_ingredient_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='cost_unit',
            field=models.CharField(choices=[('1kg', '1 kg'), ('100g', '100 g'), ('500g', '500 g'), ('1l', '1 L'), ('100ml', '100 ml'), ('500ml', '500 ml'), ('1pcs', '1 piece'), ('10pcs', '10 pieces')], default='1kg', help_text='The unit for which the cost is specified', max_length=10),
        ),
        migrations.AddField(
            model_name='ingredientrecipe',
            name='display_unit',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('g', 'g'), ('l', 'L'), ('ml', 'ml'), ('pcs', 'pieces')], help_text='Unit to display/enter in recipe (optional, defaults to ingredient unit)', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('l', 'liters'), ('g', 'grams'), ('pcs', 'pieces')], default='g', max_length=3),
        ),
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='ingredient_amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount stored in base unit (kg for weight, L for volume)', max_digits=10),
        ),
    ]
