# Generated by Django 5.0.4 on 2024-05-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_alter_ingredient_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
