# Generated by Django 5.0.4 on 2025-12-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0004_ingredient_cost_unit_ingredientrecipe_display_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='ingredient_amount',
            field=models.DecimalField(decimal_places=6, help_text='Amount stored in base unit (kg for weight, L for volume)', max_digits=10),
        ),
    ]
