# Generated by Django 5.0.4 on 2026-09-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0005_alter_ingredientrecipe_ingredient_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='calories_unit',
            field=models.CharField(choices=[('1kg', '1 kg'), ('100g', '100 g'), ('500g', '500 g'), ('1l', '1 L'), ('100ml', '100 ml'), ('500ml', '500 ml'), ('1pcs', '1 piece'), ('10pcs', '10 pieces')], default='1kg', help_text='The unit for which the calories are specified', max_length=10),
        ),
    ]
