// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/app/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import TableOutlined from '/app/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { SmileOutlined, TableOutlined };
