name: Django Backend Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_USER: django
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u django --password=password"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      working-directory: ./recipe
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for MySQL to be ready
      run: |
        for i in {1..30}; do
          if mysqladmin ping -h 127.0.0.1 -u django --password=password > /dev/null 2>&1; then
            echo "MySQL is ready!"
            break
          fi
          echo "Waiting for MySQL..."
          sleep 2
        done
    - name: Install dependencies
      working-directory: ./recipe
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      working-directory: ./recipe
      env:
        USE_MYSQL: true
        MYSQL_DB: test_db
        MYSQL_USER: django
        MYSQL_PASSWORD: password
        MYSQL_HOST: 127.0.0.1
        MYSQL_PORT: 3306
      run: python manage.py migrate

    - name: Run unit tests
      working-directory: ./recipe
      env:
        USE_MYSQL: true
        MYSQL_DB: test_db
        MYSQL_USER: django
        MYSQL_PASSWORD: password
        MYSQL_HOST: 127.0.0.1
        MYSQL_PORT: 3306
      run: python manage.py test
