name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./recipe
          dockerfile: Dockerfile
          push: true
          tags: |
            vadsimus8/recipe:latest
            vadsimus8/recipe:${{ github.sha }}

  frontend:
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./recipe-fe
          dockerfile: Dockerfile
          push: true
          tags: |
            vadsimus8/recipe-fe:latest
            vadsimus8/recipe-fe:${{ github.sha }}
